from __future__ import annotations

from typing import Any, Iterable

DOMAIN = "DOMAIN"
DOMAIN_SUFFIX = "DOMAIN-SUFFIX"
RULE_TYPES = (DOMAIN, DOMAIN_SUFFIX)

# 常见多段公共后缀，用于把子域归并到站点主域名
MULTI_LABEL_SUFFIXES = frozenset(
    {
        "com.cn", "net.cn", "org.cn", "gov.cn", "edu.cn", "ac.cn", "mil.cn",
        "com.hk", "org.hk", "edu.hk", "gov.hk", "net.hk",
        "com.tw", "org.tw", "edu.tw", "gov.tw", "net.tw",
        "co.jp", "ne.jp", "or.jp", "ac.jp", "go.jp", "lg.jp",
        "co.kr", "or.kr", "ne.kr", "go.kr", "re.kr",
        "co.uk", "org.uk", "me.uk", "ac.uk", "gov.uk", "net.uk",
        "com.au", "net.au", "org.au", "edu.au", "gov.au",
        "com.sg", "net.sg", "org.sg", "edu.sg", "gov.sg",
        "com.my", "net.my", "org.my", "edu.my", "gov.my",
        "co.id", "or.id", "ac.id", "go.id", "web.id",
        "com.br", "net.br", "org.br", "com.mx", "com.ar",
        "co.in", "net.in", "org.in", "com.ru", "com.tr",
        "com.vn", "com.ph", "com.pk", "com.sa", "com.eg",
    }
)


def registrable_domain(host: str) -> str:
    """把主机名归并到站点主域名（apex）：api.weixin.qq.com -> qq.com，a.b.com.cn -> b.com.cn"""
    host = (host or "").strip().lower().strip(".")
    labels = [label for label in host.split(".") if label]
    if len(labels) <= 2:
        return host
    if ".".join(labels[-2:]) in MULTI_LABEL_SUFFIXES:
        return ".".join(labels[-3:])
    return ".".join(labels[-2:])


def normalize_rule_type(value: Any) -> str:
    """'' 表示自动判断，否则返回 DOMAIN / DOMAIN-SUFFIX"""
    text = str(value or "").strip().upper().replace("_", "-")
    if text in {"AUTO", ""}:
        return ""
    if text in {"SUFFIX", "DOMAIN-SUFFIX", "+"}:
        return DOMAIN_SUFFIX
    if text in {"DOMAIN", "EXACT", "FULL"}:
        return DOMAIN
    raise ValueError("rule_type 只能是 auto、DOMAIN 或 DOMAIN-SUFFIX")


def effective_rule_type(domain: str, override: Any = "") -> str:
    """主域名默认 DOMAIN-SUFFIX（+.domain），子域默认精确 DOMAIN。"""
    explicit = normalize_rule_type(override)
    if explicit:
        return explicit
    return DOMAIN_SUFFIX if domain == registrable_domain(domain) else DOMAIN


def rule_payload(domain: str, rule_type: str) -> str:
    return f"+.{domain}" if rule_type == DOMAIN_SUFFIX else domain


def build_rule_items(rows: Iterable[dict[str, Any]]) -> list[dict[str, Any]]:
    """把已批准的域名整理成 [{type, payload: [...]}, ...]。

    - 主域名已批准：输出 DOMAIN-SUFFIX +.主域名，其下子域被覆盖，不再重复输出。
    - 子域已批准但主域名没批准：输出精确 DOMAIN，避免把整个站点放开。
    - 网页上手动指定过类型的域名以手动值为准。
    """
    groups: dict[str, list[dict[str, Any]]] = {}
    for row in rows:
        if str(row.get("status") or "") != "approved":
            continue
        domain = str(row.get("domain") or "").strip().lower()
        if not domain:
            continue
        groups.setdefault(registrable_domain(domain), []).append(row)

    buckets: dict[str, set[str]] = {DOMAIN: set(), DOMAIN_SUFFIX: set()}
    for site, group in groups.items():
        by_domain = {str(row["domain"]).strip().lower(): row for row in group}
        apex = by_domain.get(site)
        if apex is not None and effective_rule_type(site, apex.get("rule_type")) == DOMAIN_SUFFIX:
            buckets[DOMAIN_SUFFIX].add(rule_payload(site, DOMAIN_SUFFIX))
            for domain, row in by_domain.items():
                if domain != site and normalize_rule_type(row.get("rule_type")) == DOMAIN:
                    buckets[DOMAIN].add(domain)
            continue
        for domain, row in by_domain.items():
            rule_type = effective_rule_type(domain, row.get("rule_type"))
            buckets[rule_type].add(rule_payload(domain, rule_type))

    items: list[dict[str, Any]] = []
    for rule_type in RULE_TYPES:
        payloads = sorted(buckets[rule_type])
        if payloads:
            items.append({"type": rule_type, "payload": payloads})
    return items


def render_rule_items(items: Iterable[dict[str, Any]]) -> str:
    """渲染成 Nikki/Mihomo 规则的 type/payload 文本结构。"""
    lines: list[str] = []
    for item in items:
        lines.append(f"- type: {item['type']}")
        lines.append("  payload:")
        for payload in item["payload"]:
            lines.append(f'  - "{payload}"')
        lines.append("")
    body = "\n".join(lines).rstrip("\n")
    return f"{body}\n" if body else ""


def classic_target(payload: str) -> str:
    """经典规则语法里 DOMAIN-SUFFIX 本身就包含子域，不需要 +. 前缀。"""
    return payload[2:] if payload.startswith("+.") else payload


def render_classic_rules(items: Iterable[dict[str, Any]], app_name: str = "", version: str = "") -> str:
    """渲染成经典 Clash/Mihomo 的 rules: 列表，类型同样跟着自动判断与手选走。"""
    header = f"# generated by {app_name} {version}".rstrip()
    lines = [header] if header else []
    body: list[str] = []
    for item in items:
        for payload in item["payload"]:
            body.append(f"  - {item['type']},{classic_target(payload)},DIRECT")
    if not body:
        lines.append("rules: []")
    else:
        lines.append("rules:")
        lines.extend(body)
    return "\n".join(lines) + "\n"
def exported_payloads(items: Iterable[dict[str, Any]]) -> set[str]:
    return {payload for item in items for payload in item["payload"]}


def suffix_sites(items: Iterable[dict[str, Any]]) -> set[str]:
    return {payload[2:] for item in items if item["type"] == DOMAIN_SUFFIX for payload in item["payload"] if payload.startswith("+.")}
